version: 2
updates:
  # ─── Python (pip) ─────────────────────────────
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: [ "dependencies", "pip" ]
    groups: # Group patches & minors from dev-only tools
      dev-py:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  # ─── GitHub Actions ───────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: [ "dependencies", "gh-actions" ]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
